### ISSUE TITLE
[CONSIP] Scheda A7_1_1 - Rettifica avviso > errore "TypeError: Cannot read properties of undefined (reading '0')" 

### ISSUE THREAD

**Issue by ClaudiaMarti1** [anticorruzione/npa#1917]
Salve,
nella giornata di oggi è stato effettuato un test in ambiente di qualificazione. In particolare, abbiamo tentato di inviare la rettifica di una scheda A7_1_1. Tuttavia, riceviamo il seguente errore: "TypeError: Cannot read properties of undefined (reading '0')" 

Di seguito riportiamo le evidenze emerse dai log:
2024-12-05 12:01:53,257 ERROR (AbstractAnacUnhandledIntegrationService.java:215) - [[ACTIVE] ExecuteThread: '11' for queue: 'weblogic.kernel.Default (self-tuning)']: RequestBody = {"idAvviso":"0ea86690-3459-41ba-b6b5-1e58391bafe5","idAppalto":"45037e59-d7c9-4bef-91f0-fab9eede402b","scheda":{"type":"SchedaPostPubblicazioneType","codice":{"idTipologica":"codiceScheda","codice":"A7_1_1"},"versione":"1.0","body":{"type":"SchedaA711Type","anacForm":{"appalto":{"motivoUrgenza":{"idTipologica":"motivoUrgenza","codice":"1"},"relazioneUnicaSulleProcedure":false,"opereUrbanizzazioneScomputo":false},"aggiudicazioni":[{"cig":"I003245342","afferenteInvestimentiPNRR":false,"acquisizioneCup":false,"partecipanti":[{"codiceFiscale":"vnncpi82l20h501a","denominazione":"rrrrr","ruoloOE":{"idTipologica":"ruoloOE","codice":"1"},"tipoOE":{"idTipologica":"tipoOE","codice":"1"},"idPartecipante":"be552c30-9554-4861-9b87-2a4a70785f81","paeseOperatoreEconomico":"italia","avvalimento":false,"importo":1.0}],"finanziamenti":[{"tipoFinanziamento":{"idTipologica":"tipoFinanziamento","codice":"A"},"importo":100000.0}]}]},"eform":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPENvbnRyYWN0QXdhcmROb3RpY2UgeG1sbnM9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOkNvbnRyYWN0QXdhcmROb3RpY2UtMiIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmNhYz0idXJuOm9hc2lzOm5hbWVzOnNwZWNpZmljYXRpb246dWJsOnNjaGVtYTp4c2Q6Q29tbW9uQWdncmVnYXRlQ29tcG9uZW50cy0yIgogICAgICAgICAgICAgICAgICAgICAgeG1sbnM6Y2JjPSJ1cm46b2FzaXM6bmFtZXM6c3BlY2lmaWNhdGlvbjp1Ymw6c2NoZW1hOnhzZDpDb21tb25CYXNpY0NvbXBvbmVudHMtMiIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmVmYWM9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb24tYWdncmVnYXRlLWNvbXBvbmVudHMvMSIKICAgICAgICAgICAgICAgICAgICAgIHhtbG5zOmVmYmM9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb24tYmFzaWMtY29tcG9uZW50cy8xIgogICAgICAgICAgICAgICAgICAgICAgeG1sbnM6ZWZleHQ9Imh0dHA6Ly9kYXRhLmV1cm9wYS5ldS9wMjcvZWZvcm1zLXVibC1leHRlbnNpb25zLzEiCiAgICAgICAgICAgICAgICAgICAgICB4bWxuczpleHQ9InVybjpvYXNpczpuYW1lczpzcGVjaWZpY2F0aW9uOnVibDpzY2hlbWE6eHNkOkNvbW1vbkV4dGVuc2lvbkNvbXBvbmVudHMtMiI+CiAgIDxleHQ6VUJMRXh0ZW5zaW9ucz4KICAgICAgPGV4dDpVQkxFeHRlbnNpb24+CiAgICAgICAgIDxleHQ6RXh0ZW5zaW9uQ29udGVudD4KICAgICAgICAgICAgPGVmZXh0OkVmb3Jtc0V4dGVuc2lvbj4KICAgICAgICAgICAgICAgPGVmYWM6Q2hhbmdlcz4KICAgICAgICAgICAgICAgICAgPGVmYmM6Q2hhbmdlZE5vdGljZUlkZW50aWZpZXI+NGNiMmJiZmEtNWIwZS00M2U0LWIyYzktN2Y2YTk4YzhlZTg5LTAxPC9lZmJjOkNoYW5nZWROb3RpY2VJZGVudGlmaWVyPgogICAgICAgICAgICAgICA8L2VmYWM6Q2hhbmdlcz4KICAgICAgICAgICAgICAgPGVmYWM6Tm90aWNlUmVzdWx0PgogICAgICAgICAgICAgICAgICA8ZWZhYzpTZXR0bGVkQ29udHJhY3Q+CiAgICAgICAgICAgICAgICAgICAgIDxjYmM6SUQgc2NoZW1lTmFtZT0iY29udHJhY3QiPkNPTi0wMDAxPC9jYmM6SUQ+CiAgICAgICAgICAgICAgICAgICAgIDxlZmFjOkNvbnRyYWN0UmVmZXJlbmNlPgogICAgICAgICAgICAgICAgICAgICAgICA8Y2JjOklEIHNjaGVtZU5hbWU9ImNvbnRyYWN0Ij5pYWNvcG88L2NiYzpJRD4KICAgICAgICAgICAgICAgICAgICAgPC9lZmFjOkNvbnRyYWN0UmVmZXJlbmNlPgogICAgICAgICAgICAgICAgICA8L2VmYWM6U2V0dGxlZENvbnRyYWN0PgogICAgICAgICAgICAgICA8L2VmYWM6Tm90aWNlUmVzdWx0PgogICAgICAgICAgICAgICA8ZWZhYzpOb3RpY2VTdWJUeXBlPgogICAgICAgICAgICAgICAgICA8Y2JjOlN1YlR5cGVDb2RlIGxpc3ROYW1lPSJub3RpY2Utc3VidHlwZSI+MjU8L2NiYzpTdWJUeXBlQ29kZT4KICAgICAgICAgICAgICAgPC9lZmFjOk5vdGljZVN1YlR5cGU+CiAgICAgICAgICAgICAgIDxlZmFjOk9yZ2FuaXphdGlvbnM+CiAgICAgICAgICAgICAgICAgIDxlZmFjOk9yZ2FuaXphdGlvbj4KICAgICAgICAgICAgICAgICAgICAgPGVmYWM6Q29tcGFueT4KICAgICAgICAgICAgICAgICAgICAgICAgPGNhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPgogICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2JjOklEIHNjaGVtZU5hbWU9Im9yZ2FuaXphdGlvbiI+T1JHLTAwMDE8L2NiYzpJRD4KICAgICAgICAgICAgICAgICAgICAgICAgPC9jYWM6UGFydHlJZGVudGlmaWNhdGlvbj4KICAgICAgICAgICAgICAgICAgICAgICAgPGNhYzpQYXJ0eU5hbWU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6TmFtZSBsYW5ndWFnZUlEPSJJVEEiPkNPTVVORSBESSBVRElORTwvY2JjOk5hbWU+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvY2FjOlBhcnR5TmFtZT4KICAgICAgICAgICAgICAgICAgICAgICAgPGNhYzpQb3N0YWxBZGRyZXNzPgogICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2JjOkNpdHlOYW1lPlVESU5FPC9jYmM6Q2l0eU5hbWU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYWM6Q291bnRyeT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgPGNiYzpJZGVudGlmaWNhdGlvbkNvZGUgbGlzdE5hbWU9ImNvdW50cnkiPklUQTwvY2JjOklkZW50aWZpY2F0aW9uQ29kZT4KICAgICAgICAgICAgICAgICAgICAgICAgICAgPC9jYWM6Q291bnRyeT4KICAgICAgICAgICAgICAgICAgICAgICAgPC9jYWM6UG9zdGFsQWRkcmVzcz4KICAgICAgICAgICAgICAgICAgICAgICAgPGNhYzpDb250YWN0PgogICAgICAgICAgICAgICAgICAgICAgICAgICA8Y2JjOlRlbGVwaG9uZT4wNjU2NzMyOTg8L2NiYzpUZWxlcGhvbmU+CiAgICAgICAgICAgICAgICAgICAgICAgICAgIDxjYmM6RWxlY3Ryb25pY01haWw+dGVzdEB0ZXN0Lml0PC9jYmM6RWxlY3Ryb25pY01haWw+CiAgICAgICAgICAgICAgICAgICAgICAgIDwvY2FjOkNvbnRhY3Q+CiAgICAgICAgICAgICAgICAgICAgIDwvZWZhYzpDb21wYW55PgogICAgICAgICAgICAgICAgICA8L2VmYWM6T3JnYW5pemF0aW9uPgogICAgICAgICAgICAgICA8L2VmYWM6T3JnYW5pemF0aW9ucz4KICAgICAgICAgICAgICAgPGVmYWM6UHVibGljYXRpb24+CiAgICAgICAgICAgICAgICAgIDxlZmJjOk5vdGljZVB1YmxpY2F0aW9uSUQgc2NoZW1lTmFtZT0ib2pzLW5vdGljZS1pZCI+MTIzNDU2NzgtMTk5OTwvZWZiYzpOb3RpY2VQdWJsaWNhdGlvbklEPgogICAgICAgICAgICAgICAgICA8ZWZiYzpHYXpldHRlSUQgc2NoZW1lTmFtZT0ib2pzLWlkIj4xMjMvMTk5OTwvZWZiYzpHYXpldHRlSUQ+CiAgICAgICAgICAgICAgICAgIDxlZmJjOlB1YmxpY2F0aW9uRGF0ZT4yMDI0LTEyLTA1WjwvZWZiYzpQdWJsaWNhdGlvbkRhdGU+CiAgICAgICAgICAgICAgIDwvZWZhYzpQdWJsaWNhdGlvbj4KICAgICAgICAgICAgPC9lZmV4dDpFZm9ybXNFeHRlbnNpb24+CiAgICAgICAgIDwvZXh0OkV4dGVuc2lvbkNvbnRlbnQ+CiAgICAgIDwvZXh0OlVCTEV4dGVuc2lvbj4KICAgPC9leHQ6VUJMRXh0ZW5zaW9ucz4KICAgPGNiYzpVQkxWZXJzaW9uSUQ+Mi4zPC9jYmM6VUJMVmVyc2lvbklEPgogICA8Y2JjOkN1c3RvbWl6YXRpb25JRD5lZm9ybXMtc2RrLTEuOTwvY2JjOkN1c3RvbWl6YXRpb25JRD4KICAgPGNiYzpJRCBzY2hlbWVOYW1lPSJub3RpY2UtaWQiPjNkYzNhYmYxLWVmMjQtNDU1Yy05ODU2LTU3YjZlOTkyMjdjMzwvY2JjOklEPgogICA8Y2JjOkNvbnRyYWN0Rm9sZGVySUQ+MGVhZjIxZTUtNjk1NC00MDdkLTkxYjUtNGMzNmJhNTQ5MzAzPC9jYmM6Q29udHJhY3RGb2xkZXJJRD4KICAgPGNiYzpJc3N1ZURhdGU+MjAyNC0xMi0wNVo8L2NiYzpJc3N1ZURhdGU+CiAgIDxjYmM6SXNzdWVUaW1lPjExOjAxOjUzWjwvY2JjOklzc3VlVGltZT4KICAgPGNiYzpWZXJzaW9uSUQ+MDE8L2NiYzpWZXJzaW9uSUQ+CiAgIDxjYmM6UmVxdWVzdGVkUHVibGljYXRpb25EYXRlPjIwMjQtMTItMDVaPC9jYmM6UmVxdWVzdGVkUHVibGljYXRpb25EYXRlPgogICA8Y2JjOlJlZ3VsYXRvcnlEb21haW4+b3RoZXI8L2NiYzpSZWd1bGF0b3J5RG9tYWluPgogICA8Y2JjOk5vdGljZVR5cGVDb2RlIGxpc3ROYW1lPSJkaXItYXdhLXByZSI+dmVhdDwvY2JjOk5vdGljZVR5cGVDb2RlPgogICA8Y2JjOk5vdGljZUxhbmd1YWdlQ29kZT5JVEE8L2NiYzpOb3RpY2VMYW5ndWFnZUNvZGU+CiAgIDxjYWM6Q29udHJhY3RpbmdQYXJ0eT4KICAgICAgPGNhYzpQYXJ0eT4KICAgICAgICAgPGNhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPgogICAgICAgICAgICA8Y2JjOklEIHNjaGVtZU5hbWU9Im9yZ2FuaXphdGlvbiI+T1JHLTAwMDE8L2NiYzpJRD4KICAgICAgICAgPC9jYWM6UGFydHlJZGVudGlmaWNhdGlvbj4KICAgICAgPC9jYWM6UGFydHk+CiAgIDwvY2FjOkNvbnRyYWN0aW5nUGFydHk+CiAgIDxjYWM6VGVuZGVyaW5nVGVybXM+CiAgICAgIDxjYWM6UHJvY3VyZW1lbnRMZWdpc2xhdGlvbkRvY3VtZW50UmVmZXJlbmNlPgogICAgICAgICA8Y2JjOklEPkxvY2FsTGVnYWxCYXNpczwvY2JjOklEPgogICAgICA8L2NhYzpQcm9jdXJlbWVudExlZ2lzbGF0aW9uRG9jdW1lbnRSZWZlcmVuY2U+CiAgICAgIDxjYWM6UHJvY3VyZW1lbnRMZWdpc2xhdGlvbkRvY3VtZW50UmVmZXJlbmNlPgogICAgICAgICA8Y2JjOklEPkNyb3NzQm9yZGVyTGF3PC9jYmM6SUQ+CiAgICAgIDwvY2FjOlByb2N1cmVtZW50TGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgPC9jYWM6VGVuZGVyaW5nVGVybXM+CiAgIDxjYWM6VGVuZGVyaW5nUHJvY2Vzcz4KICAgICAgPGNiYzpQcm9jZWR1cmVDb2RlIGxpc3ROYW1lPSJwcm9jdXJlbWVudC1wcm9jZWR1cmUtdHlwZSI+bmVnLXdvLWNhbGw8L2NiYzpQcm9jZWR1cmVDb2RlPgogICA8L2NhYzpUZW5kZXJpbmdQcm9jZXNzPgogICA8Y2FjOlByb2N1cmVtZW50UHJvamVjdD4KICAgICAgPGNiYzpJRCBzY2hlbWVOYW1lPSJJbnRlcm5hbElEIj5ERUZBVUxUX1ZBTFVFX0NIQU5HRV9NRTwvY2JjOklEPgogICAgICA8Y2JjOk5hbWUgbGFuZ3VhZ2VJRD0iSVRBIj5mZmZmPC9jYmM6TmFtZT4KICAgICAgPGNiYzpEZXNjcmlwdGlvbiBsYW5ndWFnZUlEPSJJVEEiPmZmZmZmZmZmZmZmPC9jYmM6RGVzY3JpcHRpb24+CiAgICAgIDxjYmM6UHJvY3VyZW1lbnRUeXBlQ29kZSBsaXN0TmFtZT0iY29udHJhY3QtbmF0dXJlIj5zdXBwbGllczwvY2JjOlByb2N1cmVtZW50VHlwZUNvZGU+CiAgICAgIDxjYWM6TWFpbkNvbW1vZGl0eUNsYXNzaWZpY2F0aW9uPgogICAgICAgICA8Y2JjOkl0ZW1DbGFzc2lmaWNhdGlvbkNvZGUgbGlzdE5hbWU9ImNwdiI+MzQ5NDYyMjE8L2NiYzpJdGVtQ2xhc3NpZmljYXRpb25Db2RlPgogICAgICA8L2NhYzpNYWluQ29tbW9kaXR5Q2xhc3NpZmljYXRpb24+CiAgIDwvY2FjOlByb2N1cmVtZW50UHJvamVjdD4KICAgPGNhYzpQcm9jdXJlbWVudFByb2plY3RMb3Q+CiAgICAgIDxjYmM6SUQgc2NoZW1lTmFtZT0iTG90Ij5MT1QtMDAwMTwvY2JjOklEPgogICAgICA8Y2FjOlRlbmRlcmluZ1Rlcm1zPgogICAgICAgICA8Y2FjOkZpc2NhbExlZ2lzbGF0aW9uRG9jdW1lbnRSZWZlcmVuY2U+CiAgICAgICAgICAgIDxjYmM6SUQ+REVGQVVMVF9WQUxVRV9DSEFOR0VfTUU8L2NiYzpJRD4KICAgICAgICAgPC9jYWM6RmlzY2FsTGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgICAgICAgPGNhYzpFbnZpcm9ubWVudGFsTGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgICAgICAgICAgPGNiYzpJRD5ERUZBVUxUX1ZBTFVFX0NIQU5HRV9NRTwvY2JjOklEPgogICAgICAgICA8L2NhYzpFbnZpcm9ubWVudGFsTGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgICAgICAgPGNhYzpFbXBsb3ltZW50TGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgICAgICAgICAgPGNiYzpJRD5ERUZBVUxUX1ZBTFVFX0NIQU5HRV9NRTwvY2JjOklEPgogICAgICAgICA8L2NhYzpFbXBsb3ltZW50TGVnaXNsYXRpb25Eb2N1bWVudFJlZmVyZW5jZT4KICAgICAgICAgPGNhYzpBcHBlYWxUZXJtcz4KICAgICAgICAgICAgPGNhYzpBcHBlYWxSZWNlaXZlclBhcnR5PgogICAgICAgICAgICAgICA8Y2FjOlBhcnR5SWRlbnRpZmljYXRpb24+CiAgICAgICAgICAgICAgICAgIDxjYmM6SUQgc2NoZW1lTmFtZT0ib3JnYW5pemF0aW9uIj5PUkctMDAwMTwvY2JjOklEPgogICAgICAgICAgICAgICA8L2NhYzpQYXJ0eUlkZW50aWZpY2F0aW9uPgogICAgICAgICAgICA8L2NhYzpBcHBlYWxSZWNlaXZlclBhcnR5PgogICAgICAgICA8L2NhYzpBcHBlYWxUZXJtcz4KICAgICAgPC9jYWM6VGVuZGVyaW5nVGVybXM+CiAgICAgIDxjYWM6VGVuZGVyaW5nUHJvY2Vzcz4KICAgICAgICAgPGNiYzpHb3Zlcm5tZW50QWdyZWVtZW50Q29uc3RyYWludEluZGljYXRvcj5mYWxzZTwvY2JjOkdvdmVybm1lbnRBZ3JlZW1lbnRDb25zdHJhaW50SW5kaWNhdG9yPgogICAgICAgICA8Y2FjOkZyYW1ld29ya0FncmVlbWVudD4KICAgICAgICAgICAgPGNhYzpTdWJzZXF1ZW50UHJvY2Vzc1RlbmRlclJlcXVpcmVtZW50PgogICAgICAgICAgICAgICA8Y2JjOk5hbWU+YnV5ZXItY2F0ZWdvcmllczwvY2JjOk5hbWU+CiAgICAgICAgICAgIDwvY2FjOlN1YnNlcXVlbnRQcm9jZXNzVGVuZGVyUmVxdWlyZW1lbnQ+CiAgICAgICAgIDwvY2FjOkZyYW1ld29ya0FncmVlbWVudD4KICAgICAgPC9jYWM6VGVuZGVyaW5nUHJvY2Vzcz4KICAgICAgPGNhYzpQcm9jdXJlbWVudFByb2plY3Q+CiAgICAgICAgIDxjYmM6SUQgc2NoZW1lTmFtZT0iSW50ZXJuYWxJRCI+TE9ULTAwMDE8L2NiYzpJRD4KICAgICAgICAgPGNiYzpOYW1lIGxhbmd1YWdlSUQ9IklUQSI+TE9ULTAwMDE8L2NiYzpOYW1lPgogICAgICAgICA8Y2JjOkRlc2NyaXB0aW9uIGxhbmd1YWdlSUQ9IklUQSI+TE9ULTAwMDE8L2NiYzpEZXNjcmlwdGlvbj4KICAgICAgICAgPGNiYzpQcm9jdXJlbWVudFR5cGVDb2RlIGxpc3ROYW1lPSJjb250cmFjdC1uYXR1cmUiPnN1cHBsaWVzPC9jYmM6UHJvY3VyZW1lbnRUeXBlQ29kZT4KICAgICAgICAgPGNhYzpNYWluQ29tbW9kaXR5Q2xhc3NpZmljYXRpb24+CiAgICAgICAgICAgIDxjYmM6SXRlbUNsYXNzaWZpY2F0aW9uQ29kZSBsaXN0TmFtZT0iY3B2Ij4zNDk0NjIyMTwvY2JjOkl0ZW1DbGFzc2lmaWNhdGlvbkNvZGU+CiAgICAgICAgIDwvY2FjOk1haW5Db21tb2RpdHlDbGFzc2lmaWNhdGlvbj4KICAgICAgPC9jYWM6UHJvY3VyZW1lbnRQcm9qZWN0PgogICA8L2NhYzpQcm9jdXJlbWVudFByb2plY3RMb3Q+CiAgIDxjYWM6VGVuZGVyUmVzdWx0PgogICAgICA8Y2JjOkF3YXJkRGF0ZT4yMDI0LTEyLTA1WjwvY2JjOkF3YXJkRGF0ZT4KICAgPC9jYWM6VGVuZGVyUmVzdWx0Pgo8L0NvbnRyYWN0QXdhcmROb3RpY2U+Cg=="}}} - requestUrl = https://apigw-test.anticorruzione.it/modi/rest/PubblicaAvviso/v2/rettifica-avviso - headers = {Authorization=[Bearer eyJ0eXAiOiJhdCtqd3QiLCJhbGciOiJSUzI1NiIsInVzZSI6InNpZyIsImtpZCI6ImNkYjUyNTMyLWRkOTQtNDBlZi04MjRkLTljNTViMTBlNmJjOSJ9.eyJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L1B1YmJsaWNhQXZ2aXNvL3YyIiwic3ViIjoiMDFlMmVmYzQtZjJjZC00MGY0LWJhYzEtMDVlN2M2ZGNlZmJhIiwibmJmIjoxNzMzMzk2NTEzLCJkaWdlc3QiOnsiYWxnIjoiU0hBMjU2IiwidmFsdWUiOiI1MmViMjg2NzUyMjBjNTYzNjQzOTlmZDY5ZDlhZGNiYTI0ZmEyODE1OWMzYThhZGYxYTYxNWRlMDI4MDllNWVmIn0sInB1cnBvc2VJZCI6ImUzYjY1NjZkLThjNTQtNGQ0ZS04OGQ0LTRkNzI4YTg0NDA3ZiIsImlzcyI6InVhdC5pbnRlcm9wLnBhZ29wYS5pdCIsImV4cCI6MTczMzQ4MjkxMywiaWF0IjoxNzMzMzk2NTEzLCJjbGllbnRfaWQiOiIwMWUyZWZjNC1mMmNkLTQwZjQtYmFjMS0wNWU3YzZkY2VmYmEiLCJqdGkiOiI1ZDVjZjljMC04ZjFjLTQ1YmYtYTI1OC1hZTcwYWI1MzA4NjcifQ.FCRPdpjccQQF8UPg6uT9hC7zq-eKZk_6oDkSq39pQ8XV1tyzJZNnyPtRe0ZheGKnweKADHMlrCpC_6XeUI4qsxkRn1jYeN_F_5vPmGydR5UhlYEqgEerBE5OYqPqpwfkS8z_Hk5nS4fpfr28asuPUZxnX98Rx_W903pinHYzPQODcTidc6_O0oRImyWlhjT1KzzvRSpUhE6iFqAyjU0PooE2xyQKXNeds39B4EGbGPtA-I5ggxBTuGiiRsckOs-HSNq3kUF1xrJY2dIuOO0k9pNRGX0c681GuDTwq-mk7E8jLSLw7N2J4rbQnKnQ4b5sCalM2w0qXEOJqodoKznIdQ], Agid-JWT-TrackingEvidence=[eyJraWQiOiJvbjJVTmFCbGxQSlhaZDV4amdPMXoxV2QyeFVRYUItRHFtRFhaZEFiUlRBIiwiYWxnIjoiUlMyNTYiLCJ0eXAiOiJKV1QifQ.eyJqdGkiOiJkZTNhMTM4Ni1mNDM5LTQyYTMtYjg2My02MTVmMDQ2Nzc0NDciLCJhdWQiOiJodHRwczovL2FwaWd3LXRlc3QuYW50aWNvcnJ1emlvbmUuaXQvbW9kaS9yZXN0L1B1YmJsaWNhQXZ2aXNvL3YyIiwidXNlckNvZGljZUZpc2NhbGUiOiJWTk5DUEk4MkwyMEg1MDFBIiwidXNlclJvbGUiOiJSUCIsInVzZXJMb2EiOiIzIiwidXNlcklkcFR5cGUiOiJTUElEIiwiU0FDb2RpY2VGaXNjYWxlIjoiOTAxNjg2NTAzMDciLCJTQWNvZGljZUFVU0EiOiI5MDAwMTU1NTg2IiwicmVnQ29kaWNlUGlhdHRhZm9ybWEiOiIwMDAwMDA5IiwicmVnQ29kaWNlQ29tcG9uZW50ZSI6IjAwMDAwMTAiLCJidXNpbmVzc0Zsb3dJRCI6IjQ1MDM3ZTU5LWQ3YzktNGJlZi05MWYwLWZhYjllZWRlNDAyYiIsInRyYWNlSUQiOiJkZmUzNWJjYS01OTkzLTQwOWYtOTAzNS1jYjg5YTEwY2ZhZjQiLCJzcGFuSUQiOiJmMDM4Mzc2NC00ZTMwLTRkYjctOGVlMy1kZjI4MDI1NDcxOTIiLCJwdXJwb3NlSWQiOiJlM2I2NTY2ZC04YzU0LTRkNGUtODhkNC00ZDcyOGE4NDQwN2YiLCJpYXQiOjE3MzMzOTY1MTMsImV4cCI6MTczMzQwMDExMywibmJmIjoxNzMzMzk2NTEzfQ.2sCVrAvZBp0B8H0WlFcmdMvoYmM5y2j67D0UG4NJm3OBORRixz-i7GCbniY3dO-mkMlq8FPZb90wo1-eYXaexayZ2RxxrMFrJdkiKCi9dv3JH3Juwe2DPp8ul30if8OpzKhCUOgzbqTIORga7JVon3AfquWggVzD6N-7gCmvIw6gGWuej2vQnsABG8H2lz9JE_7wIZ4zHoi1qiOEpTl4X22aoFg_TIFlNM9cCamiGIj5XEzgmkyEOAjMdG4bLKEQ99bpVKIcJmO3L00dBXYI9nEbLTFq6IBFBxdql3ZmjRdXhjVdzCk0rULQeH0fDdvc5jwh3T1ATR656_szaeA4Lw], Content-Type=[application/json;charset=UTF-8], } - method = POST - Timestamp=1733396513255 - Taken=2 ms  - Thread=70 - ResponseHeaders - 
org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://apigw-test.anticorruzione.it/modi/rest/PubblicaAvviso/v2/rettifica-avviso": apigw-test.anticorruzione.it:443 failed to respond; nested exception is org.apache.http.NoHttpResponseException: apigw-test.anticorruzione.it:443 failed to respond
    at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:633)
    at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:580) 
I/O error on POST request for "https://apigw-test.anticorruzione.it/modi/rest/PubblicaAvviso/v2/rettifica-avviso": apigw-test.anticorruzione.it:443 failed to respond; nested exception is org.apache.http.NoHttpResponseException

 Grazie mille

**Comment by anac-uscp** [comment]
<p>Gentile utente,</p>

<p>Per la casistica riportata in oggetto, sono stati effettuati dei test con esito positivo. La invitiamo pertanto a riprovare.<br>
<br>
Restiamo a disposizione.<br>
<br>
Cordiali saluti</p>
